# Generated by Django 5.2 on 2025-04-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msd_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('emaik', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=5000)),
            ],
        ),
    ]
