# Generated by Django 5.2 on 2025-04-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_product_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
